//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceUserProfile
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class PlayerDto : object
    {
        
        private int PointsToNextLevelField;
        
        private string RankNameField;
        
        private ServiceUserProfile.PlayerStatus StatusField;
        
        private int currentPointsField;
        
        private string emailField;
        
        private int idLevelField;
        
        private int idPlayerField;
        
        private string lastNameField;
        
        private string nameField;
        
        private string nicknameField;
        
        private string passwordField;
        
        private string pathPhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsToNextLevel
        {
            get
            {
                return this.PointsToNextLevelField;
            }
            set
            {
                this.PointsToNextLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceUserProfile.PlayerStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentPoints
        {
            get
            {
                return this.currentPointsField;
            }
            set
            {
                this.currentPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer
        {
            get
            {
                return this.idPlayerField;
            }
            set
            {
                this.idPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname
        {
            get
            {
                return this.nicknameField;
            }
            set
            {
                this.nicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto
        {
            get
            {
                return this.pathPhotoField;
            }
            set
            {
                this.pathPhotoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatus", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.Enums")]
    public enum PlayerStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InLobby = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class ServiceFaultDto : object
    {
        
        private ServiceUserProfile.ServiceErrorType ErrorTypeField;
        
        private string MessageField;
        
        private string TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceUserProfile.ServiceErrorType ErrorType
        {
            get
            {
                return this.ErrorTypeField;
            }
            set
            {
                this.ErrorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpponentConnectionLost = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoomNotFound = 44,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class SocialDto : object
    {
        
        private int IdSocialField;
        
        private int IdSocialTypeField;
        
        private string UserLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocial
        {
            get
            {
                return this.IdSocialField;
            }
            set
            {
                this.IdSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocialType
        {
            get
            {
                return this.IdSocialTypeField;
            }
            set
            {
                this.IdSocialTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLink
        {
            get
            {
                return this.UserLinkField;
            }
            set
            {
                this.UserLinkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameHistoryDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class GameHistoryDto : object
    {
        
        private string GameModeField;
        
        private string GameTimeField;
        
        private string OpponentNameField;
        
        private string PlayerNameField;
        
        private int PointsEarnedField;
        
        private string ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode
        {
            get
            {
                return this.GameModeField;
            }
            set
            {
                this.GameModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameTime
        {
            get
            {
                return this.GameTimeField;
            }
            set
            {
                this.GameTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpponentName
        {
            get
            {
                return this.OpponentNameField;
            }
            set
            {
                this.OpponentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsEarned
        {
            get
            {
                return this.PointsEarnedField;
            }
            set
            {
                this.PointsEarnedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUserProfile.IUserProfile")]
    public interface IUserProfile
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerById", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerByIdServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<ServiceUserProfile.PlayerDto> GetPlayerByIdAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayer", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdatePlayerServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task UpdatePlayerAsync(ServiceUserProfile.PlayerDto playerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerSocialsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerSocialsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<ServiceUserProfile.SocialDto[]> GetPlayerSocialsAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdatePlayerSocials", ReplyAction="http://tempuri.org/IUserProfile/UpdatePlayerSocialsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdatePlayerSocialsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task UpdatePlayerSocialsAsync(int idPlayer, ServiceUserProfile.SocialDto[] socials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/UpdateProfilePicture", ReplyAction="http://tempuri.org/IUserProfile/UpdateProfilePictureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/UpdateProfilePictureServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task UpdateProfilePictureAsync(int idPlayer, string newPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfile/GetPlayerGameHistory", ReplyAction="http://tempuri.org/IUserProfile/GetPlayerGameHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceUserProfile.ServiceFaultDto), Action="http://tempuri.org/IUserProfile/GetPlayerGameHistoryServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<ServiceUserProfile.GameHistoryDto[]> GetPlayerGameHistoryAsync(int idPlayer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IUserProfileChannel : ServiceUserProfile.IUserProfile, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UserProfileClient : System.ServiceModel.ClientBase<ServiceUserProfile.IUserProfile>, ServiceUserProfile.IUserProfile
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserProfileClient() : 
                base(UserProfileClient.GetDefaultBinding(), UserProfileClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserProfile.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProfileClient(EndpointConfiguration endpointConfiguration) : 
                base(UserProfileClient.GetBindingForEndpoint(endpointConfiguration), UserProfileClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProfileClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserProfileClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProfileClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserProfileClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceUserProfile.PlayerDto> GetPlayerByIdAsync(int idPlayer)
        {
            return base.Channel.GetPlayerByIdAsync(idPlayer);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerAsync(ServiceUserProfile.PlayerDto playerDto)
        {
            return base.Channel.UpdatePlayerAsync(playerDto);
        }
        
        public System.Threading.Tasks.Task<ServiceUserProfile.SocialDto[]> GetPlayerSocialsAsync(int idPlayer)
        {
            return base.Channel.GetPlayerSocialsAsync(idPlayer);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerSocialsAsync(int idPlayer, ServiceUserProfile.SocialDto[] socials)
        {
            return base.Channel.UpdatePlayerSocialsAsync(idPlayer, socials);
        }
        
        public System.Threading.Tasks.Task UpdateProfilePictureAsync(int idPlayer, string newPath)
        {
            return base.Channel.UpdateProfilePictureAsync(idPlayer, newPath);
        }
        
        public System.Threading.Tasks.Task<ServiceUserProfile.GameHistoryDto[]> GetPlayerGameHistoryAsync(int idPlayer)
        {
            return base.Channel.GetPlayerGameHistoryAsync(idPlayer);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserProfile))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserProfile))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/userprofile");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserProfileClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserProfile);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserProfileClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserProfile);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserProfile,
        }
    }
}
