//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGuestInvitation
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class ServiceFaultDto : object
    {
        
        private ServiceGuestInvitation.ServiceErrorType ErrorTypeField;
        
        private string MessageField;
        
        private string TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGuestInvitation.ServiceErrorType ErrorType
        {
            get
            {
                return this.ErrorTypeField;
            }
            set
            {
                this.ErrorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpponentConnectionLost = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoomNotFound = 44,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGuestInvitation.IGuestInvitation")]
    public interface IGuestInvitation
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestInvitation/SendGuestInvite", ReplyAction="http://tempuri.org/IGuestInvitation/SendGuestInviteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGuestInvitation.ServiceFaultDto), Action="http://tempuri.org/IGuestInvitation/SendGuestInviteServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task SendGuestInviteAsync(string roomCode, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGuestInvitationChannel : ServiceGuestInvitation.IGuestInvitation, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GuestInvitationClient : System.ServiceModel.ClientBase<ServiceGuestInvitation.IGuestInvitation>, ServiceGuestInvitation.IGuestInvitation
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GuestInvitationClient() : 
                base(GuestInvitationClient.GetDefaultBinding(), GuestInvitationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGuestInvitation.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GuestInvitationClient(EndpointConfiguration endpointConfiguration) : 
                base(GuestInvitationClient.GetBindingForEndpoint(endpointConfiguration), GuestInvitationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GuestInvitationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GuestInvitationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GuestInvitationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GuestInvitationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GuestInvitationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SendGuestInviteAsync(string roomCode, string email)
        {
            return base.Channel.SendGuestInviteAsync(roomCode, email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGuestInvitation))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGuestInvitation))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/guest");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GuestInvitationClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGuestInvitation);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GuestInvitationClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGuestInvitation);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGuestInvitation,
        }
    }
}
