//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInvitation
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvitationSenderDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class InvitationSenderDto : object
    {
        
        private int IdPlayerField;
        
        private string NicknameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlayer
        {
            get
            {
                return this.IdPlayerField;
            }
            set
            {
                this.IdPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname
        {
            get
            {
                return this.NicknameField;
            }
            set
            {
                this.NicknameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class ServiceFaultDto : object
    {
        
        private ServiceInvitation.ServiceErrorType ErrorTypeField;
        
        private string MessageField;
        
        private string TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInvitation.ServiceErrorType ErrorType
        {
            get
            {
                return this.ErrorTypeField;
            }
            set
            {
                this.ErrorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpponentConnectionLost = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoomNotFound = 44,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInvitation.IInvitationService", CallbackContract=typeof(ServiceInvitation.IInvitationServiceCallback))]
    public interface IInvitationService
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IInvitationService/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IInvitationService/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvitationService/SendInvitation", ReplyAction="http://tempuri.org/IInvitationService/SendInvitationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceInvitation.ServiceFaultDto), Action="http://tempuri.org/IInvitationService/SendInvitationServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task SendInvitationAsync(ServiceInvitation.InvitationSenderDto sender, int idReceiver, string roomCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IInvitationServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IInvitationService/OnInvitationReceived")]
        void OnInvitationReceived(string senderNickname, string roomCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IInvitationServiceChannel : ServiceInvitation.IInvitationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class InvitationServiceClientBase : System.ServiceModel.DuplexClientBase<ServiceInvitation.IInvitationService>, ServiceInvitation.IInvitationService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InvitationServiceClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, InvitationServiceClientBase.GetDefaultBinding(), InvitationServiceClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IInvitationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvitationServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, InvitationServiceClientBase.GetBindingForEndpoint(endpointConfiguration), InvitationServiceClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvitationServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, InvitationServiceClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvitationServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, InvitationServiceClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvitationServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(int idPlayer)
        {
            return base.Channel.SubscribeAsync(idPlayer);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer)
        {
            return base.Channel.UnsubscribeAsync(idPlayer);
        }
        
        public System.Threading.Tasks.Task SendInvitationAsync(ServiceInvitation.InvitationSenderDto sender, int idReceiver, string roomCode)
        {
            return base.Channel.SendInvitationAsync(sender, idReceiver, roomCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IInvitationService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IInvitationService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8081/invitation");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InvitationServiceClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IInvitationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InvitationServiceClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IInvitationService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IInvitationService,
        }
    }
    
    public class OnInvitationReceivedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public OnInvitationReceivedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public string senderNickname
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public string roomCode
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    public partial class InvitationServiceClient : InvitationServiceClientBase
    {
        
        public InvitationServiceClient(EndpointConfiguration endpointConfiguration) : 
                this(new InvitationServiceClientCallback(), endpointConfiguration)
        {
        }
        
        private InvitationServiceClient(InvitationServiceClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public InvitationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new InvitationServiceClientCallback(), binding, remoteAddress)
        {
        }
        
        private InvitationServiceClient(InvitationServiceClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public InvitationServiceClient() : 
                this(new InvitationServiceClientCallback())
        {
        }
        
        private InvitationServiceClient(InvitationServiceClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<OnInvitationReceivedReceivedEventArgs> OnInvitationReceivedReceived;
        
        private void OnOnInvitationReceivedReceived(object state)
        {
            if ((this.OnInvitationReceivedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnInvitationReceivedReceived(this, new OnInvitationReceivedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class InvitationServiceClientCallback : object, IInvitationServiceCallback
        {
            
            private InvitationServiceClient proxy;
            
            public void Initialize(InvitationServiceClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void OnInvitationReceived(string senderNickname, string roomCode)
            {
                this.proxy.OnOnInvitationReceivedReceived(new object[] {
                            senderNickname,
                            roomCode});
            }
        }
    }
}
