//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGame
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStateDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class GameStateDto : object
    {
        
        private int CurrentTurnPlayerIdField;
        
        private ServiceGame.PlayerDto OpponentField;
        
        private int OpponentCardCountField;
        
        private ServiceGame.CardDto[] PlayerHandField;
        
        private ServiceGame.CardDto TopDiscardCardField;
        
        private int TotalGameSecondsField;
        
        private int TurnRemainingSecondsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentTurnPlayerId
        {
            get
            {
                return this.CurrentTurnPlayerIdField;
            }
            set
            {
                this.CurrentTurnPlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGame.PlayerDto Opponent
        {
            get
            {
                return this.OpponentField;
            }
            set
            {
                this.OpponentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpponentCardCount
        {
            get
            {
                return this.OpponentCardCountField;
            }
            set
            {
                this.OpponentCardCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGame.CardDto[] PlayerHand
        {
            get
            {
                return this.PlayerHandField;
            }
            set
            {
                this.PlayerHandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGame.CardDto TopDiscardCard
        {
            get
            {
                return this.TopDiscardCardField;
            }
            set
            {
                this.TopDiscardCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalGameSeconds
        {
            get
            {
                return this.TotalGameSecondsField;
            }
            set
            {
                this.TotalGameSecondsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnRemainingSeconds
        {
            get
            {
                return this.TurnRemainingSecondsField;
            }
            set
            {
                this.TurnRemainingSecondsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class PlayerDto : object
    {
        
        private int PointsToNextLevelField;
        
        private string RankNameField;
        
        private ServiceGame.PlayerStatus StatusField;
        
        private int currentPointsField;
        
        private string emailField;
        
        private int idLevelField;
        
        private int idPlayerField;
        
        private string lastNameField;
        
        private string nameField;
        
        private string nicknameField;
        
        private string passwordField;
        
        private string pathPhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsToNextLevel
        {
            get
            {
                return this.PointsToNextLevelField;
            }
            set
            {
                this.PointsToNextLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGame.PlayerStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentPoints
        {
            get
            {
                return this.currentPointsField;
            }
            set
            {
                this.currentPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer
        {
            get
            {
                return this.idPlayerField;
            }
            set
            {
                this.idPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname
        {
            get
            {
                return this.nicknameField;
            }
            set
            {
                this.nicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto
        {
            get
            {
                return this.pathPhotoField;
            }
            set
            {
                this.pathPhotoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class CardDto : object
    {
        
        private string IdField;
        
        private string ImagePathField;
        
        private int RankField;
        
        private string SuitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath
        {
            get
            {
                return this.ImagePathField;
            }
            set
            {
                this.ImagePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                this.RankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suit
        {
            get
            {
                return this.SuitField;
            }
            set
            {
                this.SuitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatus", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.Enums")]
    public enum PlayerStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InLobby = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class ServiceFaultDto : object
    {
        
        private ServiceGame.ServiceErrorType ErrorTypeField;
        
        private string MessageField;
        
        private string TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceGame.ServiceErrorType ErrorType
        {
            get
            {
                return this.ErrorTypeField;
            }
            set
            {
                this.ErrorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpponentConnectionLost = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoomNotFound = 44,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameResultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class GameResultDto : object
    {
        
        private int DurationSecondsField;
        
        private bool ErrorSavingToDatabaseField;
        
        private int GamemodeIdField;
        
        private bool IsDrawField;
        
        private int LoserIdField;
        
        private int Player1IdField;
        
        private string Player1NameField;
        
        private string Player1PathPhotoField;
        
        private int Player1ScoreField;
        
        private int Player2IdField;
        
        private string Player2NameField;
        
        private string Player2PathPhotoField;
        
        private int Player2ScoreField;
        
        private int PointsWonField;
        
        private string RoomCodeField;
        
        private int WinnerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationSeconds
        {
            get
            {
                return this.DurationSecondsField;
            }
            set
            {
                this.DurationSecondsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorSavingToDatabase
        {
            get
            {
                return this.ErrorSavingToDatabaseField;
            }
            set
            {
                this.ErrorSavingToDatabaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamemodeId
        {
            get
            {
                return this.GamemodeIdField;
            }
            set
            {
                this.GamemodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDraw
        {
            get
            {
                return this.IsDrawField;
            }
            set
            {
                this.IsDrawField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoserId
        {
            get
            {
                return this.LoserIdField;
            }
            set
            {
                this.LoserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player1Id
        {
            get
            {
                return this.Player1IdField;
            }
            set
            {
                this.Player1IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player1Name
        {
            get
            {
                return this.Player1NameField;
            }
            set
            {
                this.Player1NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player1PathPhoto
        {
            get
            {
                return this.Player1PathPhotoField;
            }
            set
            {
                this.Player1PathPhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player1Score
        {
            get
            {
                return this.Player1ScoreField;
            }
            set
            {
                this.Player1ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player2Id
        {
            get
            {
                return this.Player2IdField;
            }
            set
            {
                this.Player2IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player2Name
        {
            get
            {
                return this.Player2NameField;
            }
            set
            {
                this.Player2NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player2PathPhoto
        {
            get
            {
                return this.Player2PathPhotoField;
            }
            set
            {
                this.Player2PathPhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player2Score
        {
            get
            {
                return this.Player2ScoreField;
            }
            set
            {
                this.Player2ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsWon
        {
            get
            {
                return this.PointsWonField;
            }
            set
            {
                this.PointsWonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode
        {
            get
            {
                return this.RoomCodeField;
            }
            set
            {
                this.RoomCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerId
        {
            get
            {
                return this.WinnerIdField;
            }
            set
            {
                this.WinnerIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGame.IGame", CallbackContract=typeof(ServiceGame.IGameCallback))]
    public interface IGame
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/JoinGame", ReplyAction="http://tempuri.org/IGame/JoinGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/JoinGameServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<ServiceGame.GameStateDto> JoinGameAsync(string roomCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PlayCards", ReplyAction="http://tempuri.org/IGame/PlayCardsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/PlayCardsServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task PlayCardsAsync(string roomCode, int playerId, string[] cardIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/DrawFromDeck", ReplyAction="http://tempuri.org/IGame/DrawFromDeckResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/DrawFromDeckServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task DrawFromDeckAsync(string roomCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/DiscardCard", ReplyAction="http://tempuri.org/IGame/DiscardCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/DiscardCardServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task DiscardCardAsync(string roomCode, int playerId, string cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/LeaveGame")]
        System.Threading.Tasks.Task LeaveGameAsync(string roomCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PassTurn", ReplyAction="http://tempuri.org/IGame/PassTurnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/PassTurnServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task PassTurnAsync(string roomCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SwapDrawnCard", ReplyAction="http://tempuri.org/IGame/SwapDrawnCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceGame.ServiceFaultDto), Action="http://tempuri.org/IGame/SwapDrawnCardServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task SwapDrawnCardAsync(string roomCode, int playerId, string cardIdToDiscard);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/ReportAFK")]
        System.Threading.Tasks.Task ReportAFKAsync(string roomCode, int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGameCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyGameUpdate")]
        void NotifyGameUpdate(ServiceGame.GameStateDto newState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyOpponentDrewDeck")]
        void NotifyOpponentDrewDeck();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyOpponentDiscarded")]
        void NotifyOpponentDiscarded(ServiceGame.CardDto card);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/OnTimeUpdated")]
        void OnTimeUpdated(int gameRemainingSeconds, int turnRemainingSeconds, int currentTurnPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/OnOpponentHandUpdated")]
        void OnOpponentHandUpdated(int newCardCount);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyOpponentMeld")]
        void NotifyOpponentMeld(ServiceGame.CardDto[] meldCards);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/OnOpponentLeft")]
        void OnOpponentLeft();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyGameEnded")]
        void NotifyGameEnded(ServiceGame.GameResultDto result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/NotifyGameEndedByAFK")]
        void NotifyGameEndedByAFK(string reasonKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGameChannel : ServiceGame.IGame, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GameClientBase : System.ServiceModel.DuplexClientBase<ServiceGame.IGame>, ServiceGame.IGame
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GameClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, GameClientBase.GetDefaultBinding(), GameClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IGame.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, GameClientBase.GetBindingForEndpoint(endpointConfiguration), GameClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, GameClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, GameClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceGame.GameStateDto> JoinGameAsync(string roomCode, int playerId)
        {
            return base.Channel.JoinGameAsync(roomCode, playerId);
        }
        
        public System.Threading.Tasks.Task PlayCardsAsync(string roomCode, int playerId, string[] cardIds)
        {
            return base.Channel.PlayCardsAsync(roomCode, playerId, cardIds);
        }
        
        public System.Threading.Tasks.Task DrawFromDeckAsync(string roomCode, int playerId)
        {
            return base.Channel.DrawFromDeckAsync(roomCode, playerId);
        }
        
        public System.Threading.Tasks.Task DiscardCardAsync(string roomCode, int playerId, string cardId)
        {
            return base.Channel.DiscardCardAsync(roomCode, playerId, cardId);
        }
        
        public System.Threading.Tasks.Task LeaveGameAsync(string roomCode, int playerId)
        {
            return base.Channel.LeaveGameAsync(roomCode, playerId);
        }
        
        public System.Threading.Tasks.Task PassTurnAsync(string roomCode, int playerId)
        {
            return base.Channel.PassTurnAsync(roomCode, playerId);
        }
        
        public System.Threading.Tasks.Task SwapDrawnCardAsync(string roomCode, int playerId, string cardIdToDiscard)
        {
            return base.Channel.SwapDrawnCardAsync(roomCode, playerId, cardIdToDiscard);
        }
        
        public System.Threading.Tasks.Task ReportAFKAsync(string roomCode, int playerId)
        {
            return base.Channel.ReportAFKAsync(roomCode, playerId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IGame))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IGame))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://0.0.0.0:8081/game");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GameClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IGame);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GameClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IGame);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IGame,
        }
    }
    
    public class NotifyGameUpdateReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyGameUpdateReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceGame.GameStateDto newState
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceGame.GameStateDto)(this.results[0]));
            }
        }
    }
    
    public class NotifyOpponentDiscardedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyOpponentDiscardedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceGame.CardDto card
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceGame.CardDto)(this.results[0]));
            }
        }
    }
    
    public class OnTimeUpdatedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public OnTimeUpdatedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int gameRemainingSeconds
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        public int turnRemainingSeconds
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        public int currentTurnPlayerId
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    public class OnOpponentHandUpdatedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public OnOpponentHandUpdatedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int newCardCount
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public class NotifyOpponentMeldReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyOpponentMeldReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceGame.CardDto[] meldCards
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceGame.CardDto[])(this.results[0]));
            }
        }
    }
    
    public class NotifyGameEndedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyGameEndedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceGame.GameResultDto result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceGame.GameResultDto)(this.results[0]));
            }
        }
    }
    
    public class NotifyGameEndedByAFKReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyGameEndedByAFKReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public string reasonKey
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public partial class GameClient : GameClientBase
    {
        
        public GameClient(EndpointConfiguration endpointConfiguration) : 
                this(new GameClientCallback(), endpointConfiguration)
        {
        }
        
        private GameClient(GameClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public GameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new GameClientCallback(), binding, remoteAddress)
        {
        }
        
        private GameClient(GameClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public GameClient() : 
                this(new GameClientCallback())
        {
        }
        
        private GameClient(GameClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<NotifyGameUpdateReceivedEventArgs> NotifyGameUpdateReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> NotifyOpponentDrewDeckReceived;
        
        public event System.EventHandler<NotifyOpponentDiscardedReceivedEventArgs> NotifyOpponentDiscardedReceived;
        
        public event System.EventHandler<OnTimeUpdatedReceivedEventArgs> OnTimeUpdatedReceived;
        
        public event System.EventHandler<OnOpponentHandUpdatedReceivedEventArgs> OnOpponentHandUpdatedReceived;
        
        public event System.EventHandler<NotifyOpponentMeldReceivedEventArgs> NotifyOpponentMeldReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OnOpponentLeftReceived;
        
        public event System.EventHandler<NotifyGameEndedReceivedEventArgs> NotifyGameEndedReceived;
        
        public event System.EventHandler<NotifyGameEndedByAFKReceivedEventArgs> NotifyGameEndedByAFKReceived;
        
        private void OnNotifyGameUpdateReceived(object state)
        {
            if ((this.NotifyGameUpdateReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyGameUpdateReceived(this, new NotifyGameUpdateReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnNotifyOpponentDrewDeckReceived(object state)
        {
            if ((this.NotifyOpponentDrewDeckReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyOpponentDrewDeckReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnNotifyOpponentDiscardedReceived(object state)
        {
            if ((this.NotifyOpponentDiscardedReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyOpponentDiscardedReceived(this, new NotifyOpponentDiscardedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnOnTimeUpdatedReceived(object state)
        {
            if ((this.OnTimeUpdatedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnTimeUpdatedReceived(this, new OnTimeUpdatedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnOnOpponentHandUpdatedReceived(object state)
        {
            if ((this.OnOpponentHandUpdatedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnOpponentHandUpdatedReceived(this, new OnOpponentHandUpdatedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnNotifyOpponentMeldReceived(object state)
        {
            if ((this.NotifyOpponentMeldReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyOpponentMeldReceived(this, new NotifyOpponentMeldReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnOnOpponentLeftReceived(object state)
        {
            if ((this.OnOpponentLeftReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnOpponentLeftReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnNotifyGameEndedReceived(object state)
        {
            if ((this.NotifyGameEndedReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyGameEndedReceived(this, new NotifyGameEndedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnNotifyGameEndedByAFKReceived(object state)
        {
            if ((this.NotifyGameEndedByAFKReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyGameEndedByAFKReceived(this, new NotifyGameEndedByAFKReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class GameClientCallback : object, IGameCallback
        {
            
            private GameClient proxy;
            
            public void Initialize(GameClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void NotifyGameUpdate(ServiceGame.GameStateDto newState)
            {
                this.proxy.OnNotifyGameUpdateReceived(new object[] {
                            newState});
            }
            
            public void NotifyOpponentDrewDeck()
            {
                this.proxy.OnNotifyOpponentDrewDeckReceived(new object[0]);
            }
            
            public void NotifyOpponentDiscarded(ServiceGame.CardDto card)
            {
                this.proxy.OnNotifyOpponentDiscardedReceived(new object[] {
                            card});
            }
            
            public void OnTimeUpdated(int gameRemainingSeconds, int turnRemainingSeconds, int currentTurnPlayerId)
            {
                this.proxy.OnOnTimeUpdatedReceived(new object[] {
                            gameRemainingSeconds,
                            turnRemainingSeconds,
                            currentTurnPlayerId});
            }
            
            public void OnOpponentHandUpdated(int newCardCount)
            {
                this.proxy.OnOnOpponentHandUpdatedReceived(new object[] {
                            newCardCount});
            }
            
            public void NotifyOpponentMeld(ServiceGame.CardDto[] meldCards)
            {
                this.proxy.OnNotifyOpponentMeldReceived(new object[] {
                            meldCards});
            }
            
            public void OnOpponentLeft()
            {
                this.proxy.OnOnOpponentLeftReceived(new object[0]);
            }
            
            public void NotifyGameEnded(ServiceGame.GameResultDto result)
            {
                this.proxy.OnNotifyGameEndedReceived(new object[] {
                            result});
            }
            
            public void NotifyGameEndedByAFK(string reasonKey)
            {
                this.proxy.OnNotifyGameEndedByAFKReceived(new object[] {
                            reasonKey});
            }
        }
    }
}
