//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLobby
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class LobbyDto : object
    {
        
        private ServiceLobby.MessageDto[] ChatMessagesField;
        
        private string GameModeField;
        
        private ServiceLobby.PlayerDto[] PlayersField;
        
        private string RoomCodeField;
        
        private string StatusLobbyField;
        
        private System.Nullable<int> idGamemodeField;
        
        private int idHostPlayerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceLobby.MessageDto[] ChatMessages
        {
            get
            {
                return this.ChatMessagesField;
            }
            set
            {
                this.ChatMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameMode
        {
            get
            {
                return this.GameModeField;
            }
            set
            {
                this.GameModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceLobby.PlayerDto[] Players
        {
            get
            {
                return this.PlayersField;
            }
            set
            {
                this.PlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode
        {
            get
            {
                return this.RoomCodeField;
            }
            set
            {
                this.RoomCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusLobby
        {
            get
            {
                return this.StatusLobbyField;
            }
            set
            {
                this.StatusLobbyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idGamemode
        {
            get
            {
                return this.idGamemodeField;
            }
            set
            {
                this.idGamemodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHostPlayer
        {
            get
            {
                return this.idHostPlayerField;
            }
            set
            {
                this.idHostPlayerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class MessageDto : object
    {
        
        private string MessageField;
        
        private string NicknameField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname
        {
            get
            {
                return this.NicknameField;
            }
            set
            {
                this.NicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class PlayerDto : object
    {
        
        private int PointsToNextLevelField;
        
        private string RankNameField;
        
        private ServiceLobby.PlayerStatus StatusField;
        
        private int currentPointsField;
        
        private string emailField;
        
        private int idLevelField;
        
        private int idPlayerField;
        
        private string lastNameField;
        
        private string nameField;
        
        private string nicknameField;
        
        private string passwordField;
        
        private string pathPhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsToNextLevel
        {
            get
            {
                return this.PointsToNextLevelField;
            }
            set
            {
                this.PointsToNextLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceLobby.PlayerStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentPoints
        {
            get
            {
                return this.currentPointsField;
            }
            set
            {
                this.currentPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer
        {
            get
            {
                return this.idPlayerField;
            }
            set
            {
                this.idPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname
        {
            get
            {
                return this.nicknameField;
            }
            set
            {
                this.nicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathPhoto
        {
            get
            {
                return this.pathPhotoField;
            }
            set
            {
                this.pathPhotoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatus", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.Enums")]
    public enum PlayerStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InGame = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InLobby = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public partial class ServiceFaultDto : object
    {
        
        private ServiceLobby.ServiceErrorType ErrorTypeField;
        
        private string MessageField;
        
        private string TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceLobby.ServiceErrorType ErrorType
        {
            get
            {
                return this.ErrorTypeField;
            }
            set
            {
                this.ErrorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
        "acts")]
    public enum ServiceErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerInternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionActive = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestInviteUsed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredUserAsGuest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordFormat = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameFormat = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVerificationCode = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustDiscardToFinish = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrawn = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDiscardAction = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeckEmpty = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMeld = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotFound = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardAction = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameRuleViolation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyDiscaard = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOffline = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRequest = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostUserNotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLobbyHost = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotKickYourSelf = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisteredMail = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInGame = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInLobby = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpponentConnectionLost = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoomNotFound = 44,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestInviteUsedFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
        "racts")]
    public partial class GuestInviteUsedFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisteredUserAsGuestFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
        "racts")]
    public partial class RegisteredUserAsGuestFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLobby.ILobby", CallbackContract=typeof(ServiceLobby.ILobbyCallback))]
    public interface ILobby
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/GetLobbyState", ReplyAction="http://tempuri.org/ILobby/GetLobbyStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/GetLobbyStateServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/CreateLobby", ReplyAction="http://tempuri.org/ILobby/CreateLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/CreateLobbyServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribe", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/JoinAndSubscribeServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task<bool> JoinAndSubscribeAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuest", ReplyAction="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.GuestInviteUsedFault), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestGuestInviteUsedFaultFault", Name="GuestInviteUsedFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
            "racts")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.RegisteredUserAsGuestFault), Action="http://tempuri.org/ILobby/JoinAndSubscribeAsGuestRegisteredUserAsGuestFaultFault", Name="RegisteredUserAsGuestFault", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.FaultCont" +
            "racts")]
        System.Threading.Tasks.Task<ServiceLobby.PlayerDto> JoinAndSubscribeAsGuestAsync(string email, string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/LeaveAndUnsubscribe")]
        System.Threading.Tasks.Task LeaveAndUnsubscribeAsync(string roomCode, int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SendMessage", ReplyAction="http://tempuri.org/ILobby/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string roomCode, ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/SelectGamemode", ReplyAction="http://tempuri.org/ILobby/SelectGamemodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/SelectGamemodeServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task SelectGamemodeAsync(string roomCode, int idGamemode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/StartGame", ReplyAction="http://tempuri.org/ILobby/StartGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/StartGameServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task StartGameAsync(string roomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/KickPlayer", ReplyAction="http://tempuri.org/ILobby/KickPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceLobby.ServiceFaultDto), Action="http://tempuri.org/ILobby/KickPlayerServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/Conqui%C3%A1nServidor.Contracts.DataContr" +
            "acts")]
        System.Threading.Tasks.Task KickPlayerAsync(string roomCode, int idRequestingPlayer, int idPlayerToKick);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ILobbyCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/PlayerJoined")]
        void PlayerJoined(ServiceLobby.PlayerDto newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/PlayerLeft")]
        void PlayerLeft(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/HostLeft")]
        void HostLeft();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/MessageReceived")]
        void MessageReceived(ServiceLobby.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/NotifyGamemodeChanged")]
        void NotifyGamemodeChanged(int newGamemodeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/NotifyGameStarting")]
        void NotifyGameStarting();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobby/YouWereKicked")]
        void YouWereKicked();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobby/Ping", ReplyAction="http://tempuri.org/ILobby/PingResponse")]
        bool Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ILobbyChannel : ServiceLobby.ILobby, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LobbyClientBase : System.ServiceModel.DuplexClientBase<ServiceLobby.ILobby>, ServiceLobby.ILobby
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LobbyClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, LobbyClientBase.GetDefaultBinding(), LobbyClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_ILobby.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LobbyClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, LobbyClientBase.GetBindingForEndpoint(endpointConfiguration), LobbyClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LobbyClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, LobbyClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LobbyClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, LobbyClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LobbyClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceLobby.LobbyDto> GetLobbyStateAsync(string roomCode)
        {
            return base.Channel.GetLobbyStateAsync(roomCode);
        }
        
        public System.Threading.Tasks.Task<string> CreateLobbyAsync(int idHostPlayer)
        {
            return base.Channel.CreateLobbyAsync(idHostPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> JoinAndSubscribeAsync(string roomCode, int idPlayer)
        {
            return base.Channel.JoinAndSubscribeAsync(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task<ServiceLobby.PlayerDto> JoinAndSubscribeAsGuestAsync(string email, string roomCode)
        {
            return base.Channel.JoinAndSubscribeAsGuestAsync(email, roomCode);
        }
        
        public System.Threading.Tasks.Task LeaveAndUnsubscribeAsync(string roomCode, int idPlayer)
        {
            return base.Channel.LeaveAndUnsubscribeAsync(roomCode, idPlayer);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string roomCode, ServiceLobby.MessageDto message)
        {
            return base.Channel.SendMessageAsync(roomCode, message);
        }
        
        public System.Threading.Tasks.Task SelectGamemodeAsync(string roomCode, int idGamemode)
        {
            return base.Channel.SelectGamemodeAsync(roomCode, idGamemode);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string roomCode)
        {
            return base.Channel.StartGameAsync(roomCode);
        }
        
        public System.Threading.Tasks.Task KickPlayerAsync(string roomCode, int idRequestingPlayer, int idPlayerToKick)
        {
            return base.Channel.KickPlayerAsync(roomCode, idRequestingPlayer, idPlayerToKick);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ILobby))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ILobby))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8081/lobby");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LobbyClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_ILobby);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LobbyClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_ILobby);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_ILobby,
        }
    }
    
    public class PlayerJoinedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public PlayerJoinedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceLobby.PlayerDto newPlayer
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceLobby.PlayerDto)(this.results[0]));
            }
        }
    }
    
    public class PlayerLeftReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public PlayerLeftReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int idPlayer
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public class MessageReceivedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public MessageReceivedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceLobby.MessageDto message
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceLobby.MessageDto)(this.results[0]));
            }
        }
    }
    
    public class NotifyGamemodeChangedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public NotifyGamemodeChangedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int newGamemodeId
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public partial class LobbyClient : LobbyClientBase
    {
        
        public LobbyClient(EndpointConfiguration endpointConfiguration) : 
                this(new LobbyClientCallback(), endpointConfiguration)
        {
        }
        
        private LobbyClient(LobbyClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public LobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new LobbyClientCallback(), binding, remoteAddress)
        {
        }
        
        private LobbyClient(LobbyClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public LobbyClient() : 
                this(new LobbyClientCallback())
        {
        }
        
        private LobbyClient(LobbyClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<PlayerJoinedReceivedEventArgs> PlayerJoinedReceived;
        
        public event System.EventHandler<PlayerLeftReceivedEventArgs> PlayerLeftReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HostLeftReceived;
        
        public event System.EventHandler<MessageReceivedReceivedEventArgs> MessageReceivedReceived;
        
        public event System.EventHandler<NotifyGamemodeChangedReceivedEventArgs> NotifyGamemodeChangedReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> NotifyGameStartingReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> YouWereKickedReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PingReceived;
        
        private void OnPlayerJoinedReceived(object state)
        {
            if ((this.PlayerJoinedReceived != null))
            {
                object[] results = ((object[])(state));
                this.PlayerJoinedReceived(this, new PlayerJoinedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnPlayerLeftReceived(object state)
        {
            if ((this.PlayerLeftReceived != null))
            {
                object[] results = ((object[])(state));
                this.PlayerLeftReceived(this, new PlayerLeftReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnHostLeftReceived(object state)
        {
            if ((this.HostLeftReceived != null))
            {
                object[] results = ((object[])(state));
                this.HostLeftReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnMessageReceivedReceived(object state)
        {
            if ((this.MessageReceivedReceived != null))
            {
                object[] results = ((object[])(state));
                this.MessageReceivedReceived(this, new MessageReceivedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnNotifyGamemodeChangedReceived(object state)
        {
            if ((this.NotifyGamemodeChangedReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyGamemodeChangedReceived(this, new NotifyGamemodeChangedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnNotifyGameStartingReceived(object state)
        {
            if ((this.NotifyGameStartingReceived != null))
            {
                object[] results = ((object[])(state));
                this.NotifyGameStartingReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnYouWereKickedReceived(object state)
        {
            if ((this.YouWereKickedReceived != null))
            {
                object[] results = ((object[])(state));
                this.YouWereKickedReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnPingReceived(object state)
        {
            if ((this.PingReceived != null))
            {
                object[] results = ((object[])(state));
                this.PingReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private class LobbyClientCallback : object, ILobbyCallback
        {
            
            private LobbyClient proxy;
            
            public void Initialize(LobbyClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void PlayerJoined(ServiceLobby.PlayerDto newPlayer)
            {
                this.proxy.OnPlayerJoinedReceived(new object[] {
                            newPlayer});
            }
            
            public void PlayerLeft(int idPlayer)
            {
                this.proxy.OnPlayerLeftReceived(new object[] {
                            idPlayer});
            }
            
            public void HostLeft()
            {
                this.proxy.OnHostLeftReceived(new object[0]);
            }
            
            public void MessageReceived(ServiceLobby.MessageDto message)
            {
                this.proxy.OnMessageReceivedReceived(new object[] {
                            message});
            }
            
            public void NotifyGamemodeChanged(int newGamemodeId)
            {
                this.proxy.OnNotifyGamemodeChangedReceived(new object[] {
                            newGamemodeId});
            }
            
            public void NotifyGameStarting()
            {
                this.proxy.OnNotifyGameStartingReceived(new object[0]);
            }
            
            public void YouWereKicked()
            {
                this.proxy.OnYouWereKickedReceived(new object[0]);
            }
            
            public bool Ping()
            {
                this.proxy.OnPingReceived(new object[0]);
                return default(bool);
            }
        }
    }
}
