//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePresence
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePresence.IPresence", CallbackContract=typeof(ServicePresence.IPresenceCallback))]
    public interface IPresence
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(int idPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPresenceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/OnFriendStatusChanged")]
        void OnFriendStatusChanged(int friendId, int newStatusId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/OnFriendRequestReceived")]
        void OnFriendRequestReceived();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPresence/OnFriendListUpdated")]
        void OnFriendListUpdated();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPresenceChannel : ServicePresence.IPresence, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PresenceClientBase : System.ServiceModel.DuplexClientBase<ServicePresence.IPresence>, ServicePresence.IPresence
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PresenceClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, PresenceClientBase.GetDefaultBinding(), PresenceClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IPresence.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PresenceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, PresenceClientBase.GetBindingForEndpoint(endpointConfiguration), PresenceClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PresenceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, PresenceClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PresenceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, PresenceClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PresenceClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(int idPlayer)
        {
            return base.Channel.SubscribeAsync(idPlayer);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(int idPlayer)
        {
            return base.Channel.UnsubscribeAsync(idPlayer);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPresence))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IPresence))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://0.0.0.0:8081/presence");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PresenceClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IPresence);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PresenceClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IPresence);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IPresence,
        }
    }
    
    public class OnFriendStatusChangedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public OnFriendStatusChangedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int friendId
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        public int newStatusId
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    public partial class PresenceClient : PresenceClientBase
    {
        
        public PresenceClient(EndpointConfiguration endpointConfiguration) : 
                this(new PresenceClientCallback(), endpointConfiguration)
        {
        }
        
        private PresenceClient(PresenceClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public PresenceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new PresenceClientCallback(), binding, remoteAddress)
        {
        }
        
        private PresenceClient(PresenceClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public PresenceClient() : 
                this(new PresenceClientCallback())
        {
        }
        
        private PresenceClient(PresenceClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<OnFriendStatusChangedReceivedEventArgs> OnFriendStatusChangedReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OnFriendRequestReceivedReceived;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OnFriendListUpdatedReceived;
        
        private void OnOnFriendStatusChangedReceived(object state)
        {
            if ((this.OnFriendStatusChangedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnFriendStatusChangedReceived(this, new OnFriendStatusChangedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnOnFriendRequestReceivedReceived(object state)
        {
            if ((this.OnFriendRequestReceivedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnFriendRequestReceivedReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private void OnOnFriendListUpdatedReceived(object state)
        {
            if ((this.OnFriendListUpdatedReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnFriendListUpdatedReceived(this, new System.ComponentModel.AsyncCompletedEventArgs(null, false, null));
            }
        }
        
        private class PresenceClientCallback : object, IPresenceCallback
        {
            
            private PresenceClient proxy;
            
            public void Initialize(PresenceClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void OnFriendStatusChanged(int friendId, int newStatusId)
            {
                this.proxy.OnOnFriendStatusChangedReceived(new object[] {
                            friendId,
                            newStatusId});
            }
            
            public void OnFriendRequestReceived()
            {
                this.proxy.OnOnFriendRequestReceivedReceived(new object[0]);
            }
            
            public void OnFriendListUpdated()
            {
                this.proxy.OnOnFriendListUpdatedReceived(new object[0]);
            }
        }
    }
}
